services:
  valkey:
    image: valkey/valkey:8
    cpus: 4
    mem_limit: 1g
    ports:
      - "6379:6379"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - valkey
